version: "3"
services:
  dev:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    volumes:
      - ..:/workspace:cached
      - /workspace/node_modules
    ports:
      - "3000:3000"
    working_dir: /workspace
    command: npm run dev
