services:
  dev:
    ## Fetching the latest image from Docker hub
    image: jonfh/pokemon-weakness-finder:latest
    volumes:
      - ..:/workspace:cached
      - /workspace/node_modules
    ports:
      - "3000:3000"
    working_dir: /workspace
    command: npm run dev
