version: '3'
services:
  dev:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    volumes:
      - .:/app:cached
      - /app/node_modules
    ports:
      - "3000:3000"
    command: npm run dev
