name: Bump Version, Build, and Publish Chrome Extension

on:
  push:
    branches:
      - main

jobs:
  bump-build-publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install dependencies
        run: npm ci

      - name: Bump version in manifest.json
        run: |
          node .github/scripts/bump-version.cjs

      - name: Commit and push bumped version
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git remote set-url origin https://github-actions:${{ secrets.GH_TOKEN }}@github.com/JFHaataja/ts-pokemon-chrome-extension.git
          git add public/manifest.json
          git commit -m "chore: bump version for new release" || echo "No changes to commit"
          git push

      - name: Run build
        run: npm run build

      - name: Zip build folder
        run: |
          cd dist
          zip -r ../extension.zip .

      - name: Publish Chrome Extension
        uses: wdzeng/chrome-extension@v1.3.0
        with:
          extension-id: ${{ secrets.EXTENSION_ID }}
          client-id: ${{ secrets.GOOGLE_CLIENT_ID }}
          client-secret: ${{ secrets.GOOGLE_CLIENT_SECRET }}
          refresh-token: ${{ secrets.GOOGLE_REFRESH_TOKEN }}
          zip-path: ./extension.zip
          tester-only: false
          upload-only: false
          check-credentials-only: false
